# Generated by Django 3.0.7 on 2021-08-28 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(default='', max_length=50)),
                ('user_email', models.EmailField(default='', max_length=50)),
                ('user_message', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
