# Generated by Django 3.0.7 on 2021-08-28 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactform',
            old_name='user_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='contactform',
            old_name='user_message',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='contactform',
            old_name='user_name',
            new_name='name',
        ),
    ]
